### PR TITLE
Fix undefined behavior

### PR DESCRIPTION
**Pull request by Asd-g**

### CODE REVIEW

**Comment by erazortt** [comment]
The commit [bdb69b8](https://github.com/erazortt/DoViBaker/pull/10/commits/bdb69b891bf85faffd66beeefc9ffc426ade58a8) is not in line to the sources for implementing the mapping process. See Chapter 5.4.2.2 in [ETSI GS CCM 001 V1.1.1](https://www.etsi.org/deliver/etsi_gs/CCM/001_099/001/01.01.01_60/gs_ccm001v010101p.pdf#page=17). 
The relevant line in there is:
`pivot_idx = num_pivots_minus2[cmp]+1;`

Which is related to this line inside the code:
`int pivot_idx = num_pivots_minus1[cmp];`
while:
`num_pivots_minus1[cmp] = mapping_data->curves[cmp].num_pivots_minus2 + 1`
Thus the code and the documentation are compatible.

So how come that you think that this is wrong, and it would need the `-1` your adding there.

**Comment by Asd-g** [comment]
I tested two clips with profiles != 7 and `poly_order` and `fp_poly_coef` (https://github.com/erazortt/DoViBaker/blob/main/DoViBaker/DoViProcessor.cpp#L111-L112) sometimes are out of bounds and [here](https://github.com/erazortt/DoViBaker/blob/main/DoViBaker/DoViProcessor.cpp#L325-L327) a crash occurs.

If [this](https://github.com/erazortt/DoViBaker/blob/main/DoViBaker/DoViProcessor.cpp#L308) is not true for the whole loop, then `int pivot_idx = num_pivots_minus1[cmp]` and [`poly_order[cmp]`](https://github.com/erazortt/DoViBaker/blob/main/DoViBaker/DoViProcessor.cpp#L111) has size `poly_order[cmp][pivot_idx]`, but [`poly_order[cmp][pivot_idx]`](https://github.com/erazortt/DoViBaker/blob/main/DoViBaker/DoViProcessor.cpp#L325) here is illegal because that's the size and the last `poly_order[cmp]` member is `pivot_idx - 1`

**Comment by erazortt** [comment]
Could you provide the following output for the frame number where that crash happens:
./dovi_tool.exe info -i RPU.bin -f [framenumer]

**Comment by Asd-g** [comment]
[rr.txt](https://github.com/erazortt/DoViBaker/files/10831759/rr.txt)

**Comment by erazortt** [comment]
Yes, ok.

For later reference and to whom it may concern, the following line in Chapter 5.4.2.2 of [ETSI GS CCM 001](https://www.etsi.org/deliver/etsi_gs/CCM/001_099/001/01.01.01_60/gs_ccm001v010101p.pdf#page=17) is wrong:
`pivot_idx = num_pivots_minus2[cmp]+1;`
And must be replaced with:
`pivot_idx = num_pivots_minus2[cmp];`

The reasoning being:
The array `poly_order_minus1` is always shorter by one member than `pivots`. That is because `pivots` includes as the first member the blackpoint. Since no pixel ever has a value less then that, there are no coefficents necessay for these values and thus `poly_order_minus1` does not include them. Thus while the maximal index of the `pivots` array is indeed `num_pivots_minus2+1`, the maximal index of the `poly_order_minus1` array is only `num_pivots_minus2`.
The same is also true for `mmr_order_minus1`, its maximal index is also only `num_pivots_minus2`.

Looking at a real world sample: (Compare number of entires in `pivots` and `poly_order_minus1` with `num_pivots_minus2`)
        "num_pivots_minus2": 7,
        "pivots": [
          63,
          69,
          230,
          256,
          256,
          37,
          16,
          8,
          7
        ],
        "mapping_idc": "Polynomial",
        "poly_order_minus1": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],

**Pull request merged**
